wrn50_2:
 full_name: wide_resnet50_2

wrn101_2:
 full_name: wide_resnet101_2

resnet18:
 full_name: resnet18

resnet34:
 full_name: resnet34

resnet50:
 full_name: resnet50

inc_v3:
 full_name: inception_v3

inc_v4:
 full_name: inception_v4

bit50_1:
 full_name: resnetv2_50x1_bitm

bit101_1:
 full_name: resnetv2_101x1_bitm

vit_b:
 full_name: vit_base_patch16_224

vit_s:
 full_name: vit_small_patch16_224

vit_t:
 full_name: vit_tiny_patch16_224

deit_b:
 full_name: deit_base_patch16_224

deit_s:
 full_name: deit_small_patch16_224

deit_t:
 full_name: deit_tiny_patch16_224

swin_b:
 full_name: swin_base_patch4_window7_224

swin_s:
 full_name: swin_small_patch4_window7_224

swin_t:
 full_name: swin_tiny_patch4_window7_224

pit_b:
  full_name: pit_b_224



